/**
 * Entity registry. Drives the schema-driven ResourcePage (CRUD table + form
 * modal) and is the single source of truth for enum option lists shared with
 * the hand-built pages (Attendance, Weekly Tracker, Power Outage, Bin Book…).
 *
 * Column `type` controls rendering in <DataTable>:
 *   text | number | currency | date | datetime | badge | tags | progress | bool
 * Field `type` controls the form input in <FormModal>:
 *   text | number | select | date | time | textarea | tags
 */

export const opts = {
  workerRole: ['operator', 'supervisor', 'technician', 'quality_inspector', 'packer', 'floor_assistant', 'storekeeper', 'monogrammer', 'cutter'],
  department: ['cutting', 'sewing', 'finishing', 'packaging', 'quality', 'warehouse'],
  shift: ['morning', 'afternoon', 'night'],
  workerStatus: ['active', 'on_leave', 'terminated'],
  attendanceStatus: ['present', 'absent', 'late', 'half_day', 'on_leave'],
  weeklyDept: ['sewing', 'cutting', 'finishing', 'ironing', 'packaging_qc'],
  productCategory: ['top', 'bottom'],
  productType: ['shirts', 'pinafore', 'shorts', 'trouser', 'skirt', 'other'],
  orderStage: ['cutting', 'sewing', 'finishing', 'packaging'],
  orderStatus: ['pending', 'in_progress', 'completed', 'delayed'],
  rawUnit: ['meters', 'yards', 'kg', 'rolls'],
  rawStatus: ['in_stock', 'low_stock', 'out_of_stock'],
  productSize: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  productCat: ['shirts', 'pants', 'dresses', 'jackets', 'uniforms', 'accessories', 'other'],
  materialType: ['raw_material', 'finished_product'],
  movementType: ['stock_in', 'stock_out', 'adjustment', 'production_use', 'production_output', 'sale'],
  orderType: ['wholesale', 'retail'],
  paymentStatus: ['paid', 'partial', 'unpaid'],
  paymentMethod: ['cash', 'card', 'bank_transfer', 'mixed'],
  salesStatus: ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled'],
  customerType: ['wholesale', 'retail'],
  paymentTerms: ['net_15', 'net_30', 'net_60', 'cod'],
  supplierStatus: ['active', 'inactive'],
  expenseCategory: ['raw_materials', 'labor', 'utilities', 'maintenance', 'transport', 'rent', 'equipment', 'other'],
  binCategory: ['thread', 'zip', 'elastic', 'needle', 'tape', 'chalk', 'pencil', 'pin', 'fabric', 'other'],
  store: ['Store A', 'Store B'],
  binUnit: ['pcs', 'rolls', 'meters', 'yards', 'kg', 'boxes', 'packets'],
}

export const entities = {
  workers: {
    table: 'workers',
    title: 'Workers',
    singular: 'Worker',
    dateField: 'hire_date',
    searchKeys: ['name', 'employee_id', 'phone'],
    filters: [
      { name: 'status', options: opts.workerStatus },
      { name: 'department', options: opts.department },
      { name: 'role', options: opts.workerRole },
    ],
    columns: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'employee_id', label: 'Emp ID', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'department', label: 'Dept', type: 'text' },
      { key: 'team', label: 'Team', type: 'text' },
      { key: 'shift', label: 'Shift', type: 'text' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { name: 'name', label: 'Full name', type: 'text', required: true },
      { name: 'employee_id', label: 'Employee ID', type: 'text' },
      { name: 'role', label: 'Role', type: 'select', options: opts.workerRole },
      { name: 'department', label: 'Department', type: 'select', options: opts.department },
      { name: 'team', label: 'Team', type: 'text', placeholder: 'Team A' },
      { name: 'shift', label: 'Shift', type: 'select', options: opts.shift },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'hourly_rate', label: 'Hourly rate (₦)', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: opts.workerStatus, default: 'active' },
      { name: 'hire_date', label: 'Hire date', type: 'date' },
    ],
  },

  production_orders: {
    table: 'production_orders',
    title: 'Production',
    singular: 'Production Order',
    dateField: 'start_date',
    searchKeys: ['order_number', 'product_name', 'design_code'],
    filters: [
      { name: 'status', options: opts.orderStatus },
      { name: 'stage', options: opts.orderStage },
      { name: 'shift', options: opts.shift },
    ],
    columns: [
      { key: 'order_number', label: 'Order #', type: 'text' },
      { key: 'product_name', label: 'Product', type: 'text' },
      { key: 'stage', label: 'Stage', type: 'text' },
      { key: 'progress', label: 'Progress', type: 'progress', num: 'actual_output', den: 'target_quantity' },
      { key: 'due_date', label: 'Due', type: 'date' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { name: 'order_number', label: 'Order number', type: 'text', required: true },
      { name: 'product_name', label: 'Product name', type: 'text', required: true },
      { name: 'design_code', label: 'Design code', type: 'text' },
      { name: 'target_quantity', label: 'Target quantity', type: 'number' },
      { name: 'actual_output', label: 'Actual output', type: 'number' },
      { name: 'defects', label: 'Defects', type: 'number' },
      { name: 'waste_kg', label: 'Waste (kg)', type: 'number' },
      { name: 'shift', label: 'Shift', type: 'select', options: opts.shift },
      { name: 'stage', label: 'Stage', type: 'select', options: opts.orderStage },
      { name: 'status', label: 'Status', type: 'select', options: opts.orderStatus, default: 'pending' },
      { name: 'assigned_team', label: 'Assigned teams', type: 'tags', placeholder: 'Team A, Team B' },
      { name: 'start_date', label: 'Start date', type: 'date' },
      { name: 'due_date', label: 'Due date', type: 'date' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  raw_materials: {
    table: 'raw_materials',
    title: 'Raw Materials',
    singular: 'Material',
    dateField: 'created_at',
    searchKeys: ['fabric_type', 'color', 'batch_number', 'supplier'],
    lowStock: { qty: 'quantity', level: 'reorder_level' },
    filters: [
      { name: 'status', options: opts.rawStatus },
      { name: 'unit', options: opts.rawUnit },
    ],
    columns: [
      { key: 'fabric_type', label: 'Fabric', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'quantity', label: 'Qty', type: 'number' },
      { key: 'unit', label: 'Unit', type: 'text' },
      { key: 'reorder_level', label: 'Reorder', type: 'number' },
      { key: 'supplier', label: 'Supplier', type: 'text' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { name: 'fabric_type', label: 'Fabric type', type: 'text', required: true },
      { name: 'color', label: 'Color', type: 'text' },
      { name: 'gsm', label: 'GSM', type: 'number' },
      { name: 'cost_per_unit', label: 'Cost per unit (₦)', type: 'number' },
      { name: 'batch_number', label: 'Batch number', type: 'text' },
      { name: 'warehouse_location', label: 'Warehouse location', type: 'text' },
      { name: 'supplier', label: 'Supplier', type: 'text' },
      { name: 'quantity', label: 'Quantity', type: 'number' },
      { name: 'unit', label: 'Unit', type: 'select', options: opts.rawUnit },
      { name: 'reorder_level', label: 'Reorder level', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: opts.rawStatus, default: 'in_stock' },
    ],
  },

  finished_products: {
    table: 'finished_products',
    title: 'Finished Products',
    singular: 'Product',
    dateField: 'created_at',
    searchKeys: ['sku', 'product_name', 'design_code'],
    filters: [
      { name: 'category', options: opts.productCat },
      { name: 'size', options: opts.productSize },
    ],
    columns: [
      { key: 'sku', label: 'SKU', type: 'text' },
      { key: 'product_name', label: 'Product', type: 'text' },
      { key: 'size', label: 'Size', type: 'text' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'quantity_available', label: 'Qty', type: 'number' },
      { key: 'selling_price', label: 'Price', type: 'currency' },
    ],
    fields: [
      { name: 'sku', label: 'SKU', type: 'text' },
      { name: 'product_name', label: 'Product name', type: 'text', required: true },
      { name: 'size', label: 'Size', type: 'select', options: opts.productSize },
      { name: 'color', label: 'Color', type: 'text' },
      { name: 'design_code', label: 'Design code', type: 'text' },
      { name: 'production_batch', label: 'Production batch', type: 'text' },
      { name: 'cost_price', label: 'Cost price (₦)', type: 'number' },
      { name: 'selling_price', label: 'Selling price (₦)', type: 'number' },
      { name: 'quantity_available', label: 'Quantity available', type: 'number' },
      { name: 'category', label: 'Category', type: 'select', options: opts.productCat },
      { name: 'image_url', label: 'Image URL', type: 'text' },
    ],
  },

  stock_movements: {
    table: 'stock_movements',
    title: 'Stock Movements',
    singular: 'Movement',
    dateField: 'created_at',
    searchKeys: ['item_name', 'reference'],
    filters: [
      { name: 'movement_type', options: opts.movementType },
      { name: 'material_type', options: opts.materialType },
    ],
    columns: [
      { key: 'created_at', label: 'Date', type: 'date' },
      { key: 'item_name', label: 'Item', type: 'text' },
      { key: 'material_type', label: 'Type', type: 'text' },
      { key: 'movement_type', label: 'Movement', type: 'badge' },
      { key: 'quantity', label: 'Qty', type: 'number' },
      { key: 'reference', label: 'Reference', type: 'text' },
    ],
    fields: [
      { name: 'material_type', label: 'Material type', type: 'select', options: opts.materialType, required: true },
      { name: 'item_name', label: 'Item name', type: 'text', required: true },
      { name: 'item_id', label: 'Item ID', type: 'text' },
      { name: 'movement_type', label: 'Movement type', type: 'select', options: opts.movementType, required: true },
      { name: 'quantity', label: 'Quantity', type: 'number' },
      { name: 'reference', label: 'Reference', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  suppliers: {
    table: 'suppliers',
    title: 'Suppliers',
    singular: 'Supplier',
    dateField: 'created_at',
    searchKeys: ['name', 'contact_person', 'email'],
    filters: [
      { name: 'status', options: opts.supplierStatus },
      { name: 'payment_terms', options: opts.paymentTerms },
    ],
    columns: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'contact_person', label: 'Contact', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'payment_terms', label: 'Terms', type: 'text' },
      { key: 'rating', label: 'Rating', type: 'rating' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'contact_person', label: 'Contact person', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'materials_supplied', label: 'Materials supplied', type: 'tags', placeholder: 'Cotton, Denim' },
      { name: 'payment_terms', label: 'Payment terms', type: 'select', options: opts.paymentTerms },
      { name: 'rating', label: 'Rating (1-5)', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: opts.supplierStatus, default: 'active' },
    ],
  },

  customers: {
    table: 'customers',
    title: 'Customers',
    singular: 'Customer',
    dateField: 'created_at',
    searchKeys: ['name', 'company', 'email', 'phone'],
    filters: [{ name: 'type', options: opts.customerType }],
    columns: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'total_orders', label: 'Orders', type: 'number' },
      { key: 'total_spent', label: 'Spent', type: 'currency' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', options: opts.customerType },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'company', label: 'Company', type: 'text' },
      { name: 'credit_limit', label: 'Credit limit (₦)', type: 'number' },
      { name: 'total_orders', label: 'Total orders', type: 'number' },
      { name: 'total_spent', label: 'Total spent (₦)', type: 'number' },
    ],
  },

  expenses: {
    table: 'expenses',
    title: 'Finances',
    singular: 'Expense',
    dateField: 'date',
    searchKeys: ['description', 'approved_by'],
    filters: [{ name: 'category', options: opts.expenseCategory }],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'category', label: 'Category', type: 'badge' },
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'payment_method', label: 'Method', type: 'text' },
      { key: 'approved_by', label: 'Approved by', type: 'text' },
    ],
    fields: [
      { name: 'category', label: 'Category', type: 'select', options: opts.expenseCategory, required: true },
      { name: 'description', label: 'Description', type: 'text' },
      { name: 'amount', label: 'Amount (₦)', type: 'number', required: true },
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'payment_method', label: 'Payment method', type: 'text' },
      { name: 'receipt_url', label: 'Receipt URL', type: 'text' },
      { name: 'approved_by', label: 'Approved by', type: 'text' },
    ],
  },

  hourly_progress: {
    table: 'hourly_progress',
    title: 'Hourly Tracker',
    singular: 'Hourly Entry',
    dateField: 'date',
    searchKeys: ['worker_name', 'worker_id'],
    filters: [
      { name: 'shift', options: opts.shift },
      { name: 'department', options: opts.department },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'hour', label: 'Hour', type: 'text' },
      { key: 'worker_name', label: 'Worker', type: 'text' },
      { key: 'department', label: 'Dept', type: 'text' },
      { key: 'units_produced', label: 'Units', type: 'number' },
      { key: 'defects', label: 'Defects', type: 'number' },
      { key: 'shift', label: 'Shift', type: 'text' },
    ],
    fields: [
      { name: 'worker_name', label: 'Worker name', type: 'text', required: true },
      { name: 'worker_id', label: 'Worker ID', type: 'text' },
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'hour', label: 'Hour', type: 'time' },
      { name: 'shift', label: 'Shift', type: 'select', options: opts.shift },
      { name: 'department', label: 'Department', type: 'select', options: opts.department },
      { name: 'units_produced', label: 'Units produced', type: 'number' },
      { name: 'defects', label: 'Defects', type: 'number' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
}
